### ISSUE TITLE
Minor timetable error

### ISSUE THREAD

**Issue by AlbertBall** [Railway-Op-Sim/GB-SouthLondonAndThameslink#1] opened 2021-10-15 07:49 UTC
Hi Dan, Just started checking this but the session file won't load.  I traced it to a missing NULL at the end of the timetable - see attached file.  The timetable itself loads ok because there is an EOF after the last service, so the missing NULL is ignored, but in the session file there is text following the timetable so the NULL is needed.  I assume your timetable editor was used to generate the timetable (at least I hope it was!) in which case it should be easily fixed.  I inserted a NULL using Notepad++ and the session file loaded ok.  I have still to test the railway in detail but thought I'd let you know about this right away.

![Image3](https://user-images.githubusercontent.com/12687089/137451386-e21c4c4c-dc9f-46bf-a7fe-36f62d863b80.jpg)

**Comment by Daniel-Gill** [comment] 2021-10-15 07:58
Hi @AlbertBall, thanks for bringing this to my attention.

Looks like this is caused by my program (I did use this to generate the timetable, thankfully!).

A function in my Timetable class returns the string of the services:

````java
public String getTextTimetable() {
  String output = "";
  output += startTime.toString();
  for(Service service : services) {
      output += "\u0000" + service.toString();
  }
  return output;
}
````

I should be able to fix this quite easily. I've made an issue in the ros-json2ttb repo.

Thanks again!

**Comment by Daniel-Gill** [comment] 2021-10-15 13:40
All fixed now, thanks again for letting me know. :)

**Closed as completed by Daniel-Gill** 2021-10-15 13:40 UTC
Labels: bug
